### ISSUE TITLE
Unable to pick MacOS Installer

### ISSUE THREAD

**Issue by imvaskel** [takobaba/EFI-Opencore-Dell-7280#1]
Hello!
I thank you for releasing your config, but I'm having a slight problem.
Whenever I boot into the picker, I'm unable to select the MacOs Installer -- because it doesn't exist as an option.

**Comment by takobaba** [comment]
Thats really weird! Do you not see anything or you see some options? can you list what you see maybe a screenshot?

**Comment by imvaskel** [comment]
Sorry for the late response, I could only see the USB opencore I booted off. I wish I could be more help but ended up just making my own version of this with yours as a guide, thanks though!
